//! The [`Document`] type: the entry point that owns the package and the parsed
//! per-part trees.

use std::io::{Cursor, Read, Seek, Write};
use std::path::Path;

use crate::error::Result;
use crate::opc::{Package, parse_relationships};
use crate::xml::XmlTree;

use super::table::build_table;
use super::{NodeId, Paragraph, PartId, Table, WML_MAIN_URIS, is_wml_element};

/// An embedded blank document, generated by python-docx (`Document().save(...)`) with
/// nothing added — the same trick python-docx uses with its `default.docx`, so creating
/// and editing share one code path.
const BLANK_TEMPLATE: &[u8] = include_bytes!("templates/blank.docx");

/// One parsed part of the package: its name, its mutable tree, the prefix it maps to the
/// WordprocessingML main URI, and whether it has been modified (and so must be
/// re-serialized on save).
///
/// The main document part is parsed eagerly at index `0`; header and footer parts are
/// parsed lazily and appended on first access. A part that is parsed but never mutated
/// keeps `modified == false`, so [`Document::save`] passes its original bytes through
/// unchanged — reading a header does not dirty it.
#[derive(Debug, Clone)]
struct ParsedPart {
    /// Package part name, e.g. `word/document.xml` or `word/header1.xml`.
    part_name: String,
    /// Parsed tree of the part.
    tree: XmlTree,
    /// Prefix this part's root maps to the WordprocessingML main URI (usually `w`, or
    /// empty when the main namespace is the default). Used when creating elements.
    wml_prefix: String,
    /// Set true the first time a mutating accessor hands out mutation capability for this
    /// part. Only a modified part re-serializes its tree on save.
    modified: bool,
}

/// A WordprocessingML document: a `.docx` opened (or created) for reading and editing.
///
/// A `Document` owns its [`Package`] and the parsed trees of the parts it has touched.
/// The main document part is parsed eagerly; header and footer parts are parsed lazily on
/// first access (see [`Section::header`](crate::Section::header)) and cached. Every other
/// part stays as raw bytes and passes through untouched on save. Handles ([`Paragraph`],
/// [`Run`](crate::Run), [`Table`], …) are obtained from a `Document` and take it back — by
/// shared reference to read, by mutable reference to edit — and each carries the id of the
/// part it belongs to, so a handle into a header edits the header, not the body.
///
/// # Fidelity
///
/// Opening a document and saving it without touching anything rewrites nothing: a part's
/// tree is re-serialized into the package only when a mutating accessor has been used on
/// that part, so an untouched round trip keeps every part byte-identical. Because parts
/// are tracked independently, editing (say) a header re-serializes *only* the header part;
/// `word/document.xml` and all other parts stay byte-identical.
///
/// # Examples
///
/// Read every body paragraph:
///
/// ```rust,ignore
/// use docxml::Document;
///
/// let doc = Document::open("report.docx")?;
/// for para in doc.paragraphs() {
///     println!("{}", para.text(&doc));
/// }
/// # Ok::<(), docxml::Error>(())
/// ```
///
/// Create a document from scratch and save it:
///
/// ```rust
/// use docxml::Document;
///
/// let mut doc = Document::new();
/// let p = doc.add_paragraph("Hello, ");
/// p.add_run(&mut doc, "world").bold(&mut doc, true);
/// assert_eq!(doc.paragraphs().len(), 1);
/// # let dir = std::env::temp_dir();
/// doc.save(dir.join("docxml-doctest-hello.docx"))?;
/// # Ok::<(), docxml::Error>(())
/// ```
#[derive(Debug, Clone)]
pub struct Document {
    package: Package,
    /// Parsed parts. Index `0` (`PartId::MAIN`) is always the main document part; header
    /// and footer parts are appended lazily as they are first accessed.
    parsed: Vec<ParsedPart>,
}

impl Document {
    /// Open a document from a file on disk.
    ///
    /// The main document part is located via the package relationships (never a
    /// hard-coded path) and parsed eagerly into a tree; all other parts stay raw until
    /// first accessed.
    pub fn open(path: impl AsRef<Path>) -> Result<Document> {
        Self::from_package(Package::open(path)?)
    }

    /// Read a document from any seekable reader (an in-memory buffer, a network-fetched
    /// blob, etc.).
    pub fn read(reader: impl Read + Seek) -> Result<Document> {
        Self::from_package(Package::read(reader)?)
    }

    /// Create a blank document from the embedded template.
    ///
    /// This never fails: the template is a compile-time-known asset that is known to
    /// parse. Mutating accessors ([`add_paragraph`](Self::add_paragraph) and the handle
    /// methods) build the document up from here.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// doc.add_paragraph("First line.");
    /// assert_eq!(doc.paragraphs()[0].text(&doc), "First line.");
    /// ```
    #[allow(clippy::new_without_default)]
    pub fn new() -> Document {
        Self::read(Cursor::new(BLANK_TEMPLATE))
            .expect("embedded blank template is a valid .docx that parses")
    }

    /// Build a document from an already-parsed package, parsing the main document part.
    fn from_package(package: Package) -> Result<Document> {
        let doc_part = package.main_document_part()?;
        let part_name = doc_part.name.clone();
        let tree = XmlTree::parse(&doc_part.data)?;
        let wml_prefix = detect_wml_prefix(&tree);
        Ok(Document {
            package,
            parsed: vec![ParsedPart {
                part_name,
                tree,
                wml_prefix,
                modified: false,
            }],
        })
    }

    /// Save the document to a file on disk.
    ///
    /// Every parsed part whose modified flag is set is re-serialized into its part; every
    /// other part — and every parsed-but-untouched part — is written through byte-for-byte.
    pub fn save(&self, path: impl AsRef<Path>) -> Result<()> {
        self.package_for_save().save(path)
    }

    /// Write the document to any seekable writer, with the same modified-only
    /// re-serialization as [`save`](Self::save).
    pub fn write(&self, writer: impl Write + Seek) -> Result<()> {
        self.package_for_save().write(writer)
    }

    /// The package to serialize: the original when nothing has been modified (so every
    /// part stays byte-identical), or a clone with each modified part refreshed from its
    /// tree otherwise.
    fn package_for_save(&self) -> std::borrow::Cow<'_, Package> {
        if self.parsed.iter().all(|p| !p.modified) {
            return std::borrow::Cow::Borrowed(&self.package);
        }
        let mut package = self.package.clone();
        for parsed in &self.parsed {
            if !parsed.modified {
                continue;
            }
            if let Some(part) = package.part_mut(&parsed.part_name) {
                part.data = parsed.tree.serialize();
            }
        }
        std::borrow::Cow::Owned(package)
    }

    /// The underlying OPC package.
    pub fn package(&self) -> &Package {
        &self.package
    }

    /// Read access to a parsed part's tree (used by handles).
    pub(crate) fn tree(&self, part: PartId) -> &XmlTree {
        &self.parsed[part.0 as usize].tree
    }

    /// Mutable access to a parsed part's tree. Handing out this capability marks that
    /// part modified so that [`save`](Self::save) re-serializes it.
    pub(crate) fn tree_mut(&mut self, part: PartId) -> &mut XmlTree {
        let parsed = &mut self.parsed[part.0 as usize];
        parsed.modified = true;
        &mut parsed.tree
    }

    /// Build a qualified name in a part's WordprocessingML namespace, e.g.
    /// `qn(part, "p")` → `"w:p"` (or just `"p"` when that part's main namespace is the
    /// default).
    pub(crate) fn qn(&self, part: PartId, local: &str) -> String {
        let prefix = &self.parsed[part.0 as usize].wml_prefix;
        if prefix.is_empty() {
            local.to_string()
        } else {
            format!("{prefix}:{local}")
        }
    }

    /// The main document part's name (`word/document.xml` in practice).
    pub(crate) fn main_part_name(&self) -> &str {
        &self.parsed[PartId::MAIN.0 as usize].part_name
    }

    /// Ensure the package part named `part_name` is parsed and cached, returning its
    /// [`PartId`]. A part already parsed (including the main part) returns its existing
    /// id; otherwise the raw part is parsed, appended, and its new id returned.
    ///
    /// Parsing alone does **not** mark the part modified — a lazily parsed part that is
    /// only read stays byte-identical on save. Returns `None` when the package has no such
    /// part or its bytes do not parse as XML.
    pub(crate) fn ensure_part(&mut self, part_name: &str) -> Option<PartId> {
        if let Some(i) = self.parsed.iter().position(|p| p.part_name == part_name) {
            return Some(PartId(i as u16));
        }
        let part = self.package.part(part_name)?;
        let tree = XmlTree::parse(&part.data).ok()?;
        let wml_prefix = detect_wml_prefix(&tree);
        let id = PartId(self.parsed.len() as u16);
        self.parsed.push(ParsedPart {
            part_name: part_name.to_string(),
            tree,
            wml_prefix,
            modified: false,
        });
        Some(id)
    }

    /// Resolve a relationship `r:id` referenced from the part named `source_part` to the
    /// target part's package name.
    ///
    /// The relationships live in the *part-level* rels part — `_rels/<basename>.rels` in
    /// the source part's own directory (for `word/document.xml`, that is
    /// `word/_rels/document.xml.rels`). Targets there are stored relative to the source
    /// part's directory; this joins them and normalizes `.`, `..`, and a leading `/`
    /// (package-absolute) into a plain package part name. Returns `None` when the rels
    /// part is missing/unparsable or no relationship has that id.
    pub(crate) fn resolve_rel_target(&self, source_part: &str, r_id: &str) -> Option<String> {
        let rels_name = rels_part_name(source_part);
        let rels_part = self.package.part(&rels_name)?;
        let rels = parse_relationships(&rels_part.data).ok()?;
        let rel = rels.iter().find(|r| r.id == r_id)?;
        Some(resolve_part_path(source_part, &rel.target))
    }

    /// The `w:body` element, if present.
    fn body(&self) -> Option<NodeId> {
        let tree = self.tree(PartId::MAIN);
        let root = tree.root();
        tree.children(root)
            .iter()
            .copied()
            .find(|&c| is_wml_element(tree, c, "body"))
    }

    /// The document's body-level paragraphs, in order.
    ///
    /// These are the direct `w:p` children of `w:body` — matching python-docx's
    /// `Document.paragraphs`. Paragraphs nested inside tables are intentionally *not*
    /// included at this milestone.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// doc.add_paragraph("one");
    /// doc.add_paragraph("two");
    /// let texts: Vec<String> = doc.paragraphs().iter().map(|p| p.text(&doc)).collect();
    /// assert_eq!(texts, ["one", "two"]);
    /// ```
    pub fn paragraphs(&self) -> Vec<Paragraph> {
        let Some(body) = self.body() else {
            return Vec::new();
        };
        let tree = self.tree(PartId::MAIN);
        tree.children(body)
            .iter()
            .copied()
            .filter(|&c| is_wml_element(tree, c, "p"))
            .map(|c| Paragraph::from_node(PartId::MAIN, c))
            .collect()
    }

    /// Append a new body paragraph, returning a handle to it.
    ///
    /// The paragraph is inserted before a trailing `w:sectPr` when one is a direct child
    /// of `w:body` (Word requires the body's section properties to come last). When
    /// `text` is non-empty a single run carrying it is added.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// let p = doc.add_paragraph("Signed and agreed:");
    /// assert_eq!(p.text(&doc), "Signed and agreed:");
    /// ```
    pub fn add_paragraph(&mut self, text: &str) -> Paragraph {
        let body = self.body().expect("document has a w:body");
        let name = self.qn(PartId::MAIN, "p");
        let p = self.tree_mut(PartId::MAIN).create_element(name);

        // Keep a trailing w:sectPr last, per the WordprocessingML content model.
        let index = self.body_insert_index(body);
        self.tree_mut(PartId::MAIN).insert_child(body, index, p);

        let para = Paragraph::from_node(PartId::MAIN, p);
        if !text.is_empty() {
            para.add_run(self, text);
        }
        para
    }

    /// The document's body-level tables, in order.
    ///
    /// These are the direct `w:tbl` children of `w:body` — matching python-docx's
    /// `Document.tables`. Tables nested inside a table cell are intentionally *not*
    /// included; only top-level tables appear here.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// doc.add_table(2, 3);
    /// assert_eq!(doc.tables().len(), 1);
    /// assert_eq!(doc.tables()[0].rows(&doc).len(), 2);
    /// ```
    pub fn tables(&self) -> Vec<Table> {
        let Some(body) = self.body() else {
            return Vec::new();
        };
        let tree = self.tree(PartId::MAIN);
        tree.children(body)
            .iter()
            .copied()
            .filter(|&c| is_wml_element(tree, c, "tbl"))
            .map(|c| Table::from_node(PartId::MAIN, c))
            .collect()
    }

    /// Append a new `rows` × `cols` table to the body, returning a handle to it.
    ///
    /// Like [`add_paragraph`](Self::add_paragraph), the table is inserted before a
    /// trailing `w:sectPr` when the body has one. Every cell starts with a single empty
    /// paragraph; fill them with [`Cell::set_text`](crate::Cell::set_text) or
    /// [`Cell::add_paragraph`](crate::Cell::add_paragraph). The emitted skeleton mirrors
    /// python-docx's `Document.add_table` minus the table style.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// let table = doc.add_table(1, 2);
    /// let row = table.rows(&doc)[0];
    /// assert_eq!(row.cells(&doc).len(), 2);
    /// ```
    pub fn add_table(&mut self, rows: usize, cols: usize) -> Table {
        let body = self.body().expect("document has a w:body");
        let tbl = build_table(self, PartId::MAIN, rows, cols);

        // Keep a trailing w:sectPr last, per the WordprocessingML content model.
        let index = self.body_insert_index(body);
        self.tree_mut(PartId::MAIN).insert_child(body, index, tbl);
        Table::from_node(PartId::MAIN, tbl)
    }

    /// The index at which to append body content: before a trailing `w:sectPr` if the body
    /// ends with one, else at the end.
    fn body_insert_index(&self, body: NodeId) -> usize {
        let tree = self.tree(PartId::MAIN);
        let children = tree.children(body);
        match children.last().copied() {
            Some(last) if is_wml_element(tree, last, "sectPr") => children.len() - 1,
            _ => children.len(),
        }
    }

    /// Append a heading paragraph carrying `text`, styled by level, and return it.
    ///
    /// Level `0` uses the `"Title"` style; levels `1..=9` use `"Heading{level}"`
    /// (e.g. `2` → `"Heading2"`), matching python-docx's `Document.add_heading`. These
    /// are style *ids*; the built-in blank template defines them, but an arbitrary
    /// document may not — an undefined style id still writes but renders unstyled.
    ///
    /// # Panics
    /// Panics if `level` is greater than `9`.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// let h = doc.add_heading("Chapter 1", 1);
    /// assert_eq!(h.style_id(&doc).as_deref(), Some("Heading1"));
    /// assert_eq!(doc.add_heading("Title", 0).style_id(&doc).as_deref(), Some("Title"));
    /// ```
    pub fn add_heading(&mut self, text: &str, level: u8) -> Paragraph {
        assert!(level <= 9, "heading level must be 0..=9, got {level}");
        let style_id = if level == 0 {
            "Title".to_string()
        } else {
            format!("Heading{level}")
        };
        let para = self.add_paragraph(text);
        para.set_style_id(self, &style_id);
        para
    }
}

/// Determine the prefix an element tree's root maps to a WordprocessingML main URI.
///
/// Scans the root element's namespace declarations for one bound to the transitional or
/// strict main URI, returning its prefix (empty string for the default namespace). Falls
/// back to `w` when the root declares none — the conventional prefix Word uses.
fn detect_wml_prefix(tree: &XmlTree) -> String {
    let root = tree.root();
    for (key, value) in tree.attrs(root) {
        if !WML_MAIN_URIS.contains(&value.as_str()) {
            continue;
        }
        if let Some(prefix) = key.strip_prefix("xmlns:") {
            return prefix.to_string();
        }
        if key == "xmlns" {
            return String::new();
        }
    }
    "w".to_string()
}

/// The name of the part-level relationships part for `part_name`: `_rels/<basename>.rels`
/// inside the part's own directory. `word/document.xml` → `word/_rels/document.xml.rels`;
/// a root-level `foo.xml` → `_rels/foo.xml.rels`.
fn rels_part_name(part_name: &str) -> String {
    match part_name.rfind('/') {
        Some(i) => format!("{}_rels/{}.rels", &part_name[..=i], &part_name[i + 1..]),
        None => format!("_rels/{part_name}.rels"),
    }
}

/// Resolve a relationship `target` (as written in a rels part) against the directory of
/// `source_part`, yielding a normalized package part name.
///
/// A leading `/` makes the target package-absolute (the leading slash is dropped, since
/// OPC part names carry none). Otherwise the target is relative to the source part's
/// directory; `.` and `..` segments are resolved away.
fn resolve_part_path(source_part: &str, target: &str) -> String {
    if let Some(abs) = target.strip_prefix('/') {
        return abs.to_string();
    }
    // Segments of the source part's directory (everything before the last '/').
    let mut segments: Vec<&str> = match source_part.rfind('/') {
        Some(i) => source_part[..i]
            .split('/')
            .filter(|s| !s.is_empty())
            .collect(),
        None => Vec::new(),
    };
    for seg in target.split('/') {
        match seg {
            "" | "." => {}
            ".." => {
                segments.pop();
            }
            s => segments.push(s),
        }
    }
    segments.join("/")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rels_part_name_for_word_and_root() {
        assert_eq!(
            rels_part_name("word/document.xml"),
            "word/_rels/document.xml.rels"
        );
        assert_eq!(
            rels_part_name("word/header1.xml"),
            "word/_rels/header1.xml.rels"
        );
        assert_eq!(rels_part_name("foo.xml"), "_rels/foo.xml.rels");
    }

    #[test]
    fn resolve_part_path_handles_relative_dotdot_and_absolute() {
        // Sibling in the same directory.
        assert_eq!(
            resolve_part_path("word/document.xml", "header1.xml"),
            "word/header1.xml"
        );
        // Explicit current directory.
        assert_eq!(
            resolve_part_path("word/document.xml", "./footer1.xml"),
            "word/footer1.xml"
        );
        // Parent-relative target climbs out of word/.
        assert_eq!(
            resolve_part_path("word/document.xml", "../customXml/item1.xml"),
            "customXml/item1.xml"
        );
        // Package-absolute target drops the leading slash.
        assert_eq!(
            resolve_part_path("word/document.xml", "/word/media/image1.png"),
            "word/media/image1.png"
        );
    }
}
