//! The [`Document`] type: the entry point that owns the package and the parsed
//! per-part trees.

use std::io::{Cursor, Read, Seek, Write};
use std::path::Path;

use crate::error::{Error, Result};
use crate::opc::{Package, Relationship, parse_relationships};
use crate::xml::XmlTree;

use super::table::build_table;
use super::{
    BreakType, NodeId, Paragraph, PartId, Run, Table, WML_MAIN_URIS, is_wml_element, split_qname,
};

/// The `[Content_Types].xml` package part — itself an OPC part, parsed and edited through
/// the same lazy per-part machinery as any WML part.
const CONTENT_TYPES_PART: &str = "[Content_Types].xml";
/// Namespace URI of `[Content_Types].xml`.
const CONTENT_TYPES_URI: &str = "http://schemas.openxmlformats.org/package/2006/content-types";
/// Namespace URI of OPC relationship (`.rels`) parts.
const RELATIONSHIPS_URI: &str = "http://schemas.openxmlformats.org/package/2006/relationships";

/// Relationship types identifying the styles part (transitional and strict).
const STYLES_REL_TYPES: [&str; 2] = [
    "http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles",
    "http://purl.oclc.org/ooxml/officeDocument/relationships/styles",
];

/// An embedded blank document, generated by python-docx (`Document().save(...)`) with
/// nothing added — the same trick python-docx uses with its `default.docx`, so creating
/// and editing share one code path.
const BLANK_TEMPLATE: &[u8] = include_bytes!("templates/blank.docx");

/// One parsed part of the package: its name, its mutable tree, the prefix it maps to the
/// WordprocessingML main URI, and whether it has been modified (and so must be
/// re-serialized on save).
///
/// The main document part is parsed eagerly at index `0`; header and footer parts are
/// parsed lazily and appended on first access. A part that is parsed but never mutated
/// keeps `modified == false`, so [`Document::save`] passes its original bytes through
/// unchanged — reading a header does not dirty it.
#[derive(Debug, Clone)]
struct ParsedPart {
    /// Package part name, e.g. `word/document.xml` or `word/header1.xml`.
    part_name: String,
    /// Parsed tree of the part.
    tree: XmlTree,
    /// Prefix this part's root maps to the WordprocessingML main URI (usually `w`, or
    /// empty when the main namespace is the default). Used when creating elements.
    wml_prefix: String,
    /// Set true the first time a mutating accessor hands out mutation capability for this
    /// part. Only a modified part re-serializes its tree on save.
    modified: bool,
}

/// A WordprocessingML document: a `.docx` opened (or created) for reading and editing.
///
/// A `Document` owns its [`Package`] and the parsed trees of the parts it has touched.
/// The main document part is parsed eagerly; header and footer parts are parsed lazily on
/// first access (see [`Section::header`](crate::Section::header)) and cached. Every other
/// part stays as raw bytes and passes through untouched on save. Handles ([`Paragraph`],
/// [`Run`](crate::Run), [`Table`], …) are obtained from a `Document` and take it back — by
/// shared reference to read, by mutable reference to edit — and each carries the id of the
/// part it belongs to, so a handle into a header edits the header, not the body.
///
/// # Fidelity
///
/// Opening a document and saving it without touching anything rewrites nothing: a part's
/// tree is re-serialized into the package only when a mutating accessor has been used on
/// that part, so an untouched round trip keeps every part byte-identical. Because parts
/// are tracked independently, editing (say) a header re-serializes *only* the header part;
/// `word/document.xml` and all other parts stay byte-identical.
///
/// # Examples
///
/// Read every body paragraph:
///
/// ```rust,ignore
/// use docxml::Document;
///
/// let doc = Document::open("report.docx")?;
/// for para in doc.paragraphs() {
///     println!("{}", para.text(&doc));
/// }
/// # Ok::<(), docxml::Error>(())
/// ```
///
/// Create a document from scratch and save it:
///
/// ```rust
/// use docxml::Document;
///
/// let mut doc = Document::new();
/// let p = doc.add_paragraph("Hello, ");
/// p.add_run(&mut doc, "world").bold(&mut doc, true);
/// assert_eq!(doc.paragraphs().len(), 1);
/// # let dir = std::env::temp_dir();
/// doc.save(dir.join("docxml-doctest-hello.docx"))?;
/// # Ok::<(), docxml::Error>(())
/// ```
#[derive(Debug, Clone)]
pub struct Document {
    package: Package,
    /// Parsed parts. Index `0` (`PartId::MAIN`) is always the main document part; header
    /// and footer parts are appended lazily as they are first accessed.
    parsed: Vec<ParsedPart>,
}

impl Document {
    /// Open a document from a file on disk.
    ///
    /// The main document part is located via the package relationships (never a
    /// hard-coded path) and parsed eagerly into a tree; all other parts stay raw until
    /// first accessed.
    pub fn open(path: impl AsRef<Path>) -> Result<Document> {
        Self::from_package(Package::open(path)?)
    }

    /// Read a document from any seekable reader (an in-memory buffer, a network-fetched
    /// blob, etc.).
    pub fn read(reader: impl Read + Seek) -> Result<Document> {
        Self::from_package(Package::read(reader)?)
    }

    /// Create a blank document from the embedded template.
    ///
    /// This never fails: the template is a compile-time-known asset that is known to
    /// parse. Mutating accessors ([`add_paragraph`](Self::add_paragraph) and the handle
    /// methods) build the document up from here.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// doc.add_paragraph("First line.");
    /// assert_eq!(doc.paragraphs()[0].text(&doc), "First line.");
    /// ```
    #[allow(clippy::new_without_default)]
    pub fn new() -> Document {
        Self::read(Cursor::new(BLANK_TEMPLATE))
            .expect("embedded blank template is a valid .docx that parses")
    }

    /// Build a document from an already-parsed package, parsing the main document part.
    fn from_package(package: Package) -> Result<Document> {
        let doc_part = package.main_document_part()?;
        let part_name = doc_part.name.clone();
        let tree = XmlTree::parse(&doc_part.data)?;
        let wml_prefix = detect_wml_prefix(&tree);
        Ok(Document {
            package,
            parsed: vec![ParsedPart {
                part_name,
                tree,
                wml_prefix,
                modified: false,
            }],
        })
    }

    /// Save the document to a file on disk.
    ///
    /// Every parsed part whose modified flag is set is re-serialized into its part; every
    /// other part — and every parsed-but-untouched part — is written through byte-for-byte.
    pub fn save(&self, path: impl AsRef<Path>) -> Result<()> {
        self.package_for_save().save(path)
    }

    /// Write the document to any seekable writer, with the same modified-only
    /// re-serialization as [`save`](Self::save).
    pub fn write(&self, writer: impl Write + Seek) -> Result<()> {
        self.package_for_save().write(writer)
    }

    /// The package to serialize: the original when nothing has been modified (so every
    /// part stays byte-identical), or a clone with each modified part refreshed from its
    /// tree otherwise.
    fn package_for_save(&self) -> std::borrow::Cow<'_, Package> {
        if self.parsed.iter().all(|p| !p.modified) {
            return std::borrow::Cow::Borrowed(&self.package);
        }
        let mut package = self.package.clone();
        for parsed in &self.parsed {
            if !parsed.modified {
                continue;
            }
            if let Some(part) = package.part_mut(&parsed.part_name) {
                part.data = parsed.tree.serialize();
            }
        }
        std::borrow::Cow::Owned(package)
    }

    /// The underlying OPC package.
    pub fn package(&self) -> &Package {
        &self.package
    }

    /// Read access to a parsed part's tree (used by handles).
    pub(crate) fn tree(&self, part: PartId) -> &XmlTree {
        &self.parsed[part.0 as usize].tree
    }

    /// Mutable access to a parsed part's tree. Handing out this capability marks that
    /// part modified so that [`save`](Self::save) re-serializes it.
    pub(crate) fn tree_mut(&mut self, part: PartId) -> &mut XmlTree {
        let parsed = &mut self.parsed[part.0 as usize];
        parsed.modified = true;
        &mut parsed.tree
    }

    /// Build a qualified name in a part's WordprocessingML namespace, e.g.
    /// `qn(part, "p")` → `"w:p"` (or just `"p"` when that part's main namespace is the
    /// default).
    pub(crate) fn qn(&self, part: PartId, local: &str) -> String {
        let prefix = &self.parsed[part.0 as usize].wml_prefix;
        if prefix.is_empty() {
            local.to_string()
        } else {
            format!("{prefix}:{local}")
        }
    }

    /// The main document part's name (`word/document.xml` in practice).
    pub(crate) fn main_part_name(&self) -> &str {
        &self.parsed[PartId::MAIN.0 as usize].part_name
    }

    /// Ensure the package part named `part_name` is parsed and cached, returning its
    /// [`PartId`]. A part already parsed (including the main part) returns its existing
    /// id; otherwise the raw part is parsed, appended, and its new id returned.
    ///
    /// Parsing alone does **not** mark the part modified — a lazily parsed part that is
    /// only read stays byte-identical on save. Returns `None` when the package has no such
    /// part or its bytes do not parse as XML.
    pub(crate) fn ensure_part(&mut self, part_name: &str) -> Option<PartId> {
        if let Some(i) = self.parsed.iter().position(|p| p.part_name == part_name) {
            return Some(PartId(i as u16));
        }
        let part = self.package.part(part_name)?;
        let tree = XmlTree::parse(&part.data).ok()?;
        let wml_prefix = detect_wml_prefix(&tree);
        let id = PartId(self.parsed.len() as u16);
        self.parsed.push(ParsedPart {
            part_name: part_name.to_string(),
            tree,
            wml_prefix,
            modified: false,
        });
        Some(id)
    }

    /// Resolve a relationship `r:id` referenced from the part named `source_part` to the
    /// target part's package name.
    ///
    /// The relationships live in the *part-level* rels part — `_rels/<basename>.rels` in
    /// the source part's own directory (for `word/document.xml`, that is
    /// `word/_rels/document.xml.rels`). Targets there are stored relative to the source
    /// part's directory; this joins them and normalizes `.`, `..`, and a leading `/`
    /// (package-absolute) into a plain package part name. Returns `None` when the rels
    /// part is missing/unparsable or no relationship has that id.
    pub(crate) fn resolve_rel_target(&self, source_part: &str, r_id: &str) -> Option<String> {
        let rels = self.relationships_of(source_part)?;
        let rel = rels.iter().find(|r| r.id == r_id)?;
        Some(resolve_part_path(source_part, &rel.target))
    }

    /// The relationships declared by `source_part`, preferring the in-memory parsed tree
    /// over the raw package bytes.
    ///
    /// When a relationships part has been parsed (and possibly mutated — e.g. by
    /// [`add_relationship`](Self::add_relationship)), its live tree is the source of truth;
    /// the package bytes are only refreshed on save. Reading straight from the package would
    /// miss a relationship added earlier in the same session — which
    /// [`resolve_rel_target`](Self::resolve_rel_target) needs, so that a header created and
    /// then re-resolved in one session resolves to the part just made. Falls back to parsing
    /// the package bytes when the rels part has not been parsed. Returns `None` when there is
    /// no rels part or it does not parse.
    fn relationships_of(&self, source_part: &str) -> Option<Vec<Relationship>> {
        let rels_name = rels_part_name(source_part);
        if let Some(parsed) = self.parsed.iter().find(|p| p.part_name == rels_name) {
            let tree = &parsed.tree;
            let root = tree.root();
            let rels = tree
                .children(root)
                .iter()
                .copied()
                .filter(|&c| matches!(tree.name(c), Some(n) if split_qname(n).1 == "Relationship"))
                .filter_map(|c| {
                    Some(Relationship {
                        id: tree.attr(c, "Id")?.to_string(),
                        rel_type: tree.attr(c, "Type")?.to_string(),
                        target: tree.attr(c, "Target")?.to_string(),
                        external: tree.attr(c, "TargetMode") == Some("External"),
                    })
                })
                .collect();
            return Some(rels);
        }
        let rels_part = self.package.part(&rels_name)?;
        parse_relationships(&rels_part.data).ok()
    }

    /// Add (or replace) a raw package part. A thin wrapper over
    /// [`Package::add_part`](crate::opc::Package::add_part) so features that create parts
    /// (media, and any part built from scratch) stay within the typed API. The part is not
    /// parsed — it passes through on save as raw bytes.
    pub(crate) fn add_part(&mut self, name: String, data: Vec<u8>) {
        self.package.add_part(name, data);
    }

    /// Ensure `[Content_Types].xml` declares a `<Default>` mapping `ext` (matched
    /// case-insensitively) to `content_type`, adding one if absent.
    ///
    /// The content-types part is itself an OPC part: it is parsed as a tree through the
    /// lazy per-part machinery ([`ensure_part`](Self::ensure_part)) and the new `Default`
    /// is created in that part's own namespace (respecting whatever prefix its root binds
    /// to the content-types URI — in practice the default namespace, so an unprefixed
    /// `Default`). When a matching `Default` already exists the tree is only read, so the
    /// part stays byte-identical on save; otherwise the mutation marks it modified and it
    /// re-serializes.
    pub(crate) fn ensure_content_type_default(
        &mut self,
        ext: &str,
        content_type: &str,
    ) -> Result<()> {
        let ct = self.ensure_part(CONTENT_TYPES_PART).ok_or_else(|| {
            Error::InvalidPackage("[Content_Types].xml is missing or does not parse".into())
        })?;

        // A case-insensitive Default for this extension already present? Read-only path.
        let tree = self.tree(ct);
        let root = tree.root();
        let already = tree.children(root).iter().copied().any(|c| {
            matches!(tree.name(c), Some(n) if split_qname(n).1 == "Default")
                && tree
                    .attr(c, "Extension")
                    .is_some_and(|e| e.eq_ignore_ascii_case(ext))
        });
        if already {
            return Ok(());
        }

        // Insert the new Default before the first Override, keeping Defaults grouped first
        // (the convention Word and python-docx follow); the schema permits either order.
        let prefix = root_prefix_for_uri(tree, CONTENT_TYPES_URI).unwrap_or_default();
        let name = qualify(&prefix, "Default");
        let index = tree
            .children(root)
            .iter()
            .copied()
            .position(|c| matches!(tree.name(c), Some(n) if split_qname(n).1 == "Override"))
            .unwrap_or_else(|| tree.children(root).len());

        let tree = self.tree_mut(ct);
        let el = tree.create_element(name);
        tree.set_attr(el, "Extension", ext);
        tree.set_attr(el, "ContentType", content_type);
        tree.insert_child(root, index, el);
        Ok(())
    }

    /// Ensure `[Content_Types].xml` declares an `<Override>` mapping the package part
    /// `part_name` (its package-absolute `/word/…` form) to `content_type`, adding one if
    /// absent.
    ///
    /// This is the `Override` sibling of [`ensure_content_type_default`](Self::ensure_content_type_default):
    /// where `Default` keys a content type by file *extension*, `Override` keys it by an
    /// individual part name — the form OOXML uses for the single-instance WML parts
    /// (`document.xml`, `styles.xml`, `numbering.xml`, …), whose `+xml` content types are
    /// not distinguishable by the shared `.xml` extension. The existing content-types helper
    /// handled only `Default`s, so this extends it. The new `Override` is appended after the
    /// existing children (Word groups `Default`s first, then `Override`s; appending keeps
    /// that shape since `Default`s already lead). When a matching `Override` is already
    /// present the tree is only read, so the part stays byte-identical on save.
    pub(crate) fn ensure_content_type_override(
        &mut self,
        part_name: &str,
        content_type: &str,
    ) -> Result<()> {
        let ct = self.ensure_part(CONTENT_TYPES_PART).ok_or_else(|| {
            Error::InvalidPackage("[Content_Types].xml is missing or does not parse".into())
        })?;

        let tree = self.tree(ct);
        let root = tree.root();
        let already = tree.children(root).iter().copied().any(|c| {
            matches!(tree.name(c), Some(n) if split_qname(n).1 == "Override")
                && tree.attr(c, "PartName") == Some(part_name)
        });
        if already {
            return Ok(());
        }

        let prefix = root_prefix_for_uri(tree, CONTENT_TYPES_URI).unwrap_or_default();
        let name = qualify(&prefix, "Override");

        let tree = self.tree_mut(ct);
        let el = tree.create_element(name);
        tree.set_attr(el, "PartName", part_name);
        tree.set_attr(el, "ContentType", content_type);
        tree.append_child(root, el);
        Ok(())
    }

    /// The package part name of the part reachable from the main document part by a
    /// relationship of one of `rel_types`, or `None` when there is no such relationship (or
    /// its rels part is missing / unparsable).
    ///
    /// Read-only (`&self`): resolves through [`relationships_of`](Self::relationships_of),
    /// so it sees a relationship added earlier this session (via the parsed rels tree) as
    /// well as the on-disk ones.
    pub(crate) fn part_by_rel_type(&self, rel_types: &[&str]) -> Option<String> {
        let source = self.main_part_name();
        let rels = self.relationships_of(source)?;
        let rel = rels
            .iter()
            .find(|r| rel_types.contains(&r.rel_type.as_str()))?;
        Some(resolve_part_path(source, &rel.target))
    }

    /// The `(numId, ilvl)` a paragraph *style* contributes through its `w:pPr/w:numPr`,
    /// following the `w:basedOn` chain, resolved by reading `styles.xml`.
    ///
    /// Returns `None` when there is no styles part, the style id is unknown, or no style in
    /// the `basedOn` chain defines a `w:numId`. Read-only: `styles.xml` is parsed from its
    /// raw bytes on demand (it is not one of the lazily cached WML parts), so this needs
    /// only `&self` — matching [`Paragraph::numbering`](crate::Paragraph::numbering)'s
    /// signature.
    pub(crate) fn style_numbering(&self, style_id: &str) -> Option<(u32, u32)> {
        let styles_name = self.part_by_rel_type(&STYLES_REL_TYPES)?;
        let raw = self.package.part(&styles_name)?;
        let tree = XmlTree::parse(&raw.data).ok()?;
        let prefix = detect_wml_prefix(&tree);
        let val = qualify(&prefix, "val");
        let style_id_attr = qualify(&prefix, "styleId");

        let root = tree.root();
        let mut current = style_id.to_string();
        // Bounded walk up the basedOn chain — guards against a malformed cyclic chain.
        for _ in 0..64 {
            let style = tree.children(root).iter().copied().find(|&c| {
                is_wml_element(&tree, c, "style")
                    && tree.attr(c, &style_id_attr) == Some(current.as_str())
            })?;
            if let Some(numpr) = first_child_named(&tree, style, "pPr")
                .and_then(|ppr| first_child_named(&tree, ppr, "numPr"))
            {
                if let Some(pair) = super::paragraph::read_numpr(&tree, numpr, &val) {
                    return Some(pair);
                }
            }
            current = first_child_named(&tree, style, "basedOn")
                .and_then(|b| tree.attr(b, &val))
                .map(str::to_owned)?;
        }
        None
    }

    /// Add a `<Relationship>` to `source_part`'s relationships part and return its new
    /// `rId`.
    ///
    /// The id is the smallest unused `rId<n>` computed as `max(existing) + 1` over the ids
    /// already present that match the `rId<number>` shape. The relationship is created in
    /// the rels part's own namespace (respecting its root's prefix for the relationships
    /// URI — in practice the default namespace). When `source_part` has no relationships
    /// part yet, an empty one is created from scratch via [`add_part`](Self::add_part);
    /// in our templates and fixtures `word/_rels/document.xml.rels` always exists.
    pub(crate) fn add_relationship(
        &mut self,
        source_part: &str,
        rel_type: &str,
        target: &str,
        external: bool,
    ) -> Result<String> {
        let rels_name = rels_part_name(source_part);

        // Create an empty relationships part if the source part has none.
        if self.package.part(&rels_name).is_none() {
            let empty = format!(
                "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\
                 <Relationships xmlns=\"{RELATIONSHIPS_URI}\"/>"
            );
            self.package.add_part(rels_name.clone(), empty.into_bytes());
        }

        let rels = self.ensure_part(&rels_name).ok_or_else(|| {
            Error::InvalidPackage(format!("relationships part {rels_name} does not parse"))
        })?;

        // Next free rId: max existing rId<number> + 1.
        let tree = self.tree(rels);
        let root = tree.root();
        let mut max = 0u32;
        for c in tree.children(root).iter().copied() {
            if !matches!(tree.name(c), Some(n) if split_qname(n).1 == "Relationship") {
                continue;
            }
            if let Some(n) = tree
                .attr(c, "Id")
                .and_then(|id| id.strip_prefix("rId"))
                .and_then(|d| d.parse::<u32>().ok())
            {
                max = max.max(n);
            }
        }
        let new_id = format!("rId{}", max + 1);

        let prefix = root_prefix_for_uri(tree, RELATIONSHIPS_URI).unwrap_or_default();
        let name = qualify(&prefix, "Relationship");

        let tree = self.tree_mut(rels);
        let el = tree.create_element(name);
        tree.set_attr(el, "Id", new_id.clone());
        tree.set_attr(el, "Type", rel_type);
        tree.set_attr(el, "Target", target);
        if external {
            tree.set_attr(el, "TargetMode", "External");
        }
        tree.append_child(root, el);
        Ok(new_id)
    }

    /// The `w:body` element, if present.
    fn body(&self) -> Option<NodeId> {
        let tree = self.tree(PartId::MAIN);
        let root = tree.root();
        tree.children(root)
            .iter()
            .copied()
            .find(|&c| is_wml_element(tree, c, "body"))
    }

    /// The document's body-level paragraphs, in order.
    ///
    /// These are the direct `w:p` children of `w:body` — matching python-docx's
    /// `Document.paragraphs`. Paragraphs nested inside tables are intentionally *not*
    /// included at this milestone.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// doc.add_paragraph("one");
    /// doc.add_paragraph("two");
    /// let texts: Vec<String> = doc.paragraphs().iter().map(|p| p.text(&doc)).collect();
    /// assert_eq!(texts, ["one", "two"]);
    /// ```
    pub fn paragraphs(&self) -> Vec<Paragraph> {
        let Some(body) = self.body() else {
            return Vec::new();
        };
        let tree = self.tree(PartId::MAIN);
        tree.children(body)
            .iter()
            .copied()
            .filter(|&c| is_wml_element(tree, c, "p"))
            .map(|c| Paragraph::from_node(PartId::MAIN, c))
            .collect()
    }

    /// Append a new body paragraph, returning a handle to it.
    ///
    /// The paragraph is inserted before a trailing `w:sectPr` when one is a direct child
    /// of `w:body` (Word requires the body's section properties to come last). When
    /// `text` is non-empty a single run carrying it is added.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// let p = doc.add_paragraph("Signed and agreed:");
    /// assert_eq!(p.text(&doc), "Signed and agreed:");
    /// ```
    pub fn add_paragraph(&mut self, text: &str) -> Paragraph {
        let body = self.body().expect("document has a w:body");
        let name = self.qn(PartId::MAIN, "p");
        let p = self.tree_mut(PartId::MAIN).create_element(name);

        // Keep a trailing w:sectPr last, per the WordprocessingML content model.
        let index = self.body_insert_index(body);
        self.tree_mut(PartId::MAIN).insert_child(body, index, p);

        let para = Paragraph::from_node(PartId::MAIN, p);
        if !text.is_empty() {
            para.add_run(self, text);
        }
        para
    }

    /// The document's body-level tables, in order.
    ///
    /// These are the direct `w:tbl` children of `w:body` — matching python-docx's
    /// `Document.tables`. Tables nested inside a table cell are intentionally *not*
    /// included; only top-level tables appear here.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// doc.add_table(2, 3);
    /// assert_eq!(doc.tables().len(), 1);
    /// assert_eq!(doc.tables()[0].rows(&doc).len(), 2);
    /// ```
    pub fn tables(&self) -> Vec<Table> {
        let Some(body) = self.body() else {
            return Vec::new();
        };
        let tree = self.tree(PartId::MAIN);
        tree.children(body)
            .iter()
            .copied()
            .filter(|&c| is_wml_element(tree, c, "tbl"))
            .map(|c| Table::from_node(PartId::MAIN, c))
            .collect()
    }

    /// Append a new `rows` × `cols` table to the body, returning a handle to it.
    ///
    /// Like [`add_paragraph`](Self::add_paragraph), the table is inserted before a
    /// trailing `w:sectPr` when the body has one. Every cell starts with a single empty
    /// paragraph; fill them with [`Cell::set_text`](crate::Cell::set_text) or
    /// [`Cell::add_paragraph`](crate::Cell::add_paragraph). The emitted skeleton mirrors
    /// python-docx's `Document.add_table` minus the table style.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// let table = doc.add_table(1, 2);
    /// let row = table.rows(&doc)[0];
    /// assert_eq!(row.cells(&doc).len(), 2);
    /// ```
    pub fn add_table(&mut self, rows: usize, cols: usize) -> Table {
        let body = self.body().expect("document has a w:body");
        let tbl = build_table(self, PartId::MAIN, rows, cols);

        // Keep a trailing w:sectPr last, per the WordprocessingML content model.
        let index = self.body_insert_index(body);
        self.tree_mut(PartId::MAIN).insert_child(body, index, tbl);
        Table::from_node(PartId::MAIN, tbl)
    }

    /// The index at which to append body content: before a trailing `w:sectPr` if the body
    /// ends with one, else at the end.
    fn body_insert_index(&self, body: NodeId) -> usize {
        let tree = self.tree(PartId::MAIN);
        let children = tree.children(body);
        match children.last().copied() {
            Some(last) if is_wml_element(tree, last, "sectPr") => children.len() - 1,
            _ => children.len(),
        }
    }

    /// Append a heading paragraph carrying `text`, styled by level, and return it.
    ///
    /// Level `0` uses the `"Title"` style; levels `1..=9` use `"Heading{level}"`
    /// (e.g. `2` → `"Heading2"`), matching python-docx's `Document.add_heading`. These
    /// are style *ids*; the built-in blank template defines them, but an arbitrary
    /// document may not — an undefined style id still writes but renders unstyled.
    ///
    /// # Panics
    /// Panics if `level` is greater than `9`.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// let h = doc.add_heading("Chapter 1", 1);
    /// assert_eq!(h.style_id(&doc).as_deref(), Some("Heading1"));
    /// assert_eq!(doc.add_heading("Title", 0).style_id(&doc).as_deref(), Some("Title"));
    /// ```
    pub fn add_heading(&mut self, text: &str, level: u8) -> Paragraph {
        assert!(level <= 9, "heading level must be 0..=9, got {level}");
        let style_id = if level == 0 {
            "Title".to_string()
        } else {
            format!("Heading{level}")
        };
        let para = self.add_paragraph(text);
        para.set_style_id(self, &style_id);
        para
    }

    /// Append a paragraph whose single run carries a page break, returning the paragraph.
    ///
    /// Matches python-docx's `Document.add_page_break`: a fresh body paragraph containing
    /// one run with a `w:br w:type="page"` (and no text). Like
    /// [`add_paragraph`](Self::add_paragraph), it is inserted before a trailing `w:sectPr`.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// let p = doc.add_page_break();
    /// assert_eq!(p.runs(&doc).len(), 1);
    /// assert_eq!(p.text(&doc), "\n");
    /// ```
    pub fn add_page_break(&mut self) -> Paragraph {
        let para = self.add_paragraph("");
        let r_name = self.qn(PartId::MAIN, "r");
        let tree = self.tree_mut(PartId::MAIN);
        let r = tree.create_element(r_name);
        tree.append_child(para.node(), r);
        Run::from_node(PartId::MAIN, r).add_break(self, BreakType::Page);
        para
    }

    /// Append a bulleted list paragraph carrying `text`, and return it.
    ///
    /// python-docx parity with `Document.add_paragraph(text, style="List Bullet")`: the
    /// paragraph is given the `"ListBullet"` paragraph style, whose definition in the
    /// embedded blank template carries the bullet numbering reference (a `w:numPr` pointing
    /// at a bullet numbering in `word/numbering.xml`). It therefore renders as a bullet out
    /// of the box on a [`Document::new`] document. An arbitrary opened document may not
    /// define `"ListBullet"`; there the style id still writes but renders unstyled.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// let p = doc.add_bullet_paragraph("first point");
    /// assert_eq!(p.style_id(&doc).as_deref(), Some("ListBullet"));
    /// assert!(p.numbering(&doc).is_some());
    /// ```
    pub fn add_bullet_paragraph(&mut self, text: &str) -> Paragraph {
        let para = self.add_paragraph(text);
        para.set_style_id(self, "ListBullet");
        para
    }

    /// Append a numbered list paragraph carrying `text`, and return it.
    ///
    /// python-docx parity with `Document.add_paragraph(text, style="List Number")`: the
    /// paragraph is given the `"ListNumber"` paragraph style, whose definition in the
    /// embedded blank template carries the decimal numbering reference. It renders as a
    /// numbered item out of the box on a [`Document::new`] document. As with
    /// [`add_bullet_paragraph`](Self::add_bullet_paragraph), an opened document that does
    /// not define `"ListNumber"` writes the style id but renders unstyled.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// let p = doc.add_numbered_paragraph("first step");
    /// assert_eq!(p.style_id(&doc).as_deref(), Some("ListNumber"));
    /// assert!(p.numbering(&doc).is_some());
    /// ```
    pub fn add_numbered_paragraph(&mut self, text: &str) -> Paragraph {
        let para = self.add_paragraph(text);
        para.set_style_id(self, "ListNumber");
        para
    }
}

/// Determine the prefix an element tree's root maps to a WordprocessingML main URI.
///
/// Scans the root element's namespace declarations for one bound to the transitional or
/// strict main URI, returning its prefix (empty string for the default namespace). Falls
/// back to `w` when the root declares none — the conventional prefix Word uses.
fn detect_wml_prefix(tree: &XmlTree) -> String {
    let root = tree.root();
    for (key, value) in tree.attrs(root) {
        if !WML_MAIN_URIS.contains(&value.as_str()) {
            continue;
        }
        if let Some(prefix) = key.strip_prefix("xmlns:") {
            return prefix.to_string();
        }
        if key == "xmlns" {
            return String::new();
        }
    }
    "w".to_string()
}

/// The prefix the tree's root element binds to `uri`, or `None` when the root declares no
/// namespace with that URI. An empty string means the URI is the default namespace
/// (`xmlns="…"`), so elements in it are created unprefixed.
fn root_prefix_for_uri(tree: &XmlTree, uri: &str) -> Option<String> {
    let root = tree.root();
    for (key, value) in tree.attrs(root) {
        if value != uri {
            continue;
        }
        if let Some(prefix) = key.strip_prefix("xmlns:") {
            return Some(prefix.to_string());
        }
        if key == "xmlns" {
            return Some(String::new());
        }
    }
    None
}

/// The first direct child of `parent` that is a WordprocessingML element with the given
/// local name, or `None`.
fn first_child_named(tree: &XmlTree, parent: NodeId, local: &str) -> Option<NodeId> {
    tree.children(parent)
        .iter()
        .copied()
        .find(|&c| is_wml_element(tree, c, local))
}

/// Join a prefix and local name into a qualified name: `qualify("", "Default")` →
/// `"Default"`, `qualify("ct", "Default")` → `"ct:Default"`.
fn qualify(prefix: &str, local: &str) -> String {
    if prefix.is_empty() {
        local.to_string()
    } else {
        format!("{prefix}:{local}")
    }
}

/// The name of the part-level relationships part for `part_name`: `_rels/<basename>.rels`
/// inside the part's own directory. `word/document.xml` → `word/_rels/document.xml.rels`;
/// a root-level `foo.xml` → `_rels/foo.xml.rels`.
fn rels_part_name(part_name: &str) -> String {
    match part_name.rfind('/') {
        Some(i) => format!("{}_rels/{}.rels", &part_name[..=i], &part_name[i + 1..]),
        None => format!("_rels/{part_name}.rels"),
    }
}

/// Resolve a relationship `target` (as written in a rels part) against the directory of
/// `source_part`, yielding a normalized package part name.
///
/// A leading `/` makes the target package-absolute (the leading slash is dropped, since
/// OPC part names carry none). Otherwise the target is relative to the source part's
/// directory; `.` and `..` segments are resolved away.
fn resolve_part_path(source_part: &str, target: &str) -> String {
    if let Some(abs) = target.strip_prefix('/') {
        return abs.to_string();
    }
    // Segments of the source part's directory (everything before the last '/').
    let mut segments: Vec<&str> = match source_part.rfind('/') {
        Some(i) => source_part[..i]
            .split('/')
            .filter(|s| !s.is_empty())
            .collect(),
        None => Vec::new(),
    };
    for seg in target.split('/') {
        match seg {
            "" | "." => {}
            ".." => {
                segments.pop();
            }
            s => segments.push(s),
        }
    }
    segments.join("/")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rels_part_name_for_word_and_root() {
        assert_eq!(
            rels_part_name("word/document.xml"),
            "word/_rels/document.xml.rels"
        );
        assert_eq!(
            rels_part_name("word/header1.xml"),
            "word/_rels/header1.xml.rels"
        );
        assert_eq!(rels_part_name("foo.xml"), "_rels/foo.xml.rels");
    }

    #[test]
    fn resolve_part_path_handles_relative_dotdot_and_absolute() {
        // Sibling in the same directory.
        assert_eq!(
            resolve_part_path("word/document.xml", "header1.xml"),
            "word/header1.xml"
        );
        // Explicit current directory.
        assert_eq!(
            resolve_part_path("word/document.xml", "./footer1.xml"),
            "word/footer1.xml"
        );
        // Parent-relative target climbs out of word/.
        assert_eq!(
            resolve_part_path("word/document.xml", "../customXml/item1.xml"),
            "customXml/item1.xml"
        );
        // Package-absolute target drops the leading slash.
        assert_eq!(
            resolve_part_path("word/document.xml", "/word/media/image1.png"),
            "word/media/image1.png"
        );
    }
}
