//! The [`Document`] type: the entry point that owns the package and the parsed
//! main-document tree.

use std::io::{Cursor, Read, Seek, Write};
use std::path::Path;

use crate::error::Result;
use crate::opc::Package;
use crate::xml::{NodeId, XmlTree};

use super::{Paragraph, WML_MAIN_URIS, is_wml_element};

/// An embedded blank document, generated by python-docx (`Document().save(...)`) with
/// nothing added — the same trick python-docx uses with its `default.docx`, so creating
/// and editing share one code path.
const BLANK_TEMPLATE: &[u8] = include_bytes!("templates/blank.docx");

/// A WordprocessingML document: a `.docx` opened (or created) for reading and editing.
///
/// A `Document` owns its [`Package`] and the eagerly parsed
/// [`XmlTree`](crate::xml::XmlTree) of the main document part; every other part stays as
/// raw bytes and passes through untouched on save. Handles ([`Paragraph`], [`Run`]) are
/// obtained from a `Document` and take it back — by shared reference to read, by mutable
/// reference to edit.
///
/// # Fidelity
///
/// Opening a document and saving it without touching anything rewrites nothing: the
/// tree is re-serialized into its part only when a mutating accessor has been used, so
/// an untouched round trip keeps `word/document.xml` byte-identical.
///
/// # Examples
///
/// Read every body paragraph:
///
/// ```rust,ignore
/// use docxml::Document;
///
/// let doc = Document::open("report.docx")?;
/// for para in doc.paragraphs() {
///     println!("{}", para.text(&doc));
/// }
/// # Ok::<(), docxml::Error>(())
/// ```
///
/// Create a document from scratch and save it:
///
/// ```rust
/// use docxml::Document;
///
/// let mut doc = Document::new();
/// let p = doc.add_paragraph("Hello, ");
/// p.add_run(&mut doc, "world").bold(&mut doc, true);
/// assert_eq!(doc.paragraphs().len(), 1);
/// # let dir = std::env::temp_dir();
/// doc.save(dir.join("docxml-doctest-hello.docx"))?;
/// # Ok::<(), docxml::Error>(())
/// ```
#[derive(Debug, Clone)]
pub struct Document {
    package: Package,
    /// Name of the main document part in the package, e.g. `word/document.xml`.
    doc_part_name: String,
    /// Parsed tree of the main document part.
    tree: XmlTree,
    /// Prefix the document root maps to the WordprocessingML main URI (usually `w`, or
    /// empty when the main namespace is the default). Used when creating elements.
    wml_prefix: String,
    /// Set true the first time a mutating accessor hands out mutation capability. Only a
    /// modified document re-serializes its tree on save.
    modified: bool,
}

impl Document {
    /// Open a document from a file on disk.
    ///
    /// The main document part is located via the package relationships (never a
    /// hard-coded path) and parsed eagerly into a tree; all other parts stay raw.
    pub fn open(path: impl AsRef<Path>) -> Result<Document> {
        Self::from_package(Package::open(path)?)
    }

    /// Read a document from any seekable reader (an in-memory buffer, a network-fetched
    /// blob, etc.).
    pub fn read(reader: impl Read + Seek) -> Result<Document> {
        Self::from_package(Package::read(reader)?)
    }

    /// Create a blank document from the embedded template.
    ///
    /// This never fails: the template is a compile-time-known asset that is known to
    /// parse. Mutating accessors ([`add_paragraph`](Self::add_paragraph) and the handle
    /// methods) build the document up from here.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// doc.add_paragraph("First line.");
    /// assert_eq!(doc.paragraphs()[0].text(&doc), "First line.");
    /// ```
    #[allow(clippy::new_without_default)]
    pub fn new() -> Document {
        Self::read(Cursor::new(BLANK_TEMPLATE))
            .expect("embedded blank template is a valid .docx that parses")
    }

    /// Build a document from an already-parsed package.
    fn from_package(package: Package) -> Result<Document> {
        let doc_part = package.main_document_part()?;
        let doc_part_name = doc_part.name.clone();
        let tree = XmlTree::parse(&doc_part.data)?;
        let wml_prefix = detect_wml_prefix(&tree);
        Ok(Document {
            package,
            doc_part_name,
            tree,
            wml_prefix,
            modified: false,
        })
    }

    /// Save the document to a file on disk.
    ///
    /// If the document has been modified, the main document tree is re-serialized into
    /// its part; every other part — and an untouched document's main part — is written
    /// through byte-for-byte.
    pub fn save(&self, path: impl AsRef<Path>) -> Result<()> {
        self.package_for_save().save(path)
    }

    /// Write the document to any seekable writer, with the same modified-only
    /// re-serialization as [`save`](Self::save).
    pub fn write(&self, writer: impl Write + Seek) -> Result<()> {
        self.package_for_save().write(writer)
    }

    /// The package to serialize: the original when untouched (so every part stays
    /// byte-identical), or a clone with the main part refreshed from the tree when the
    /// document has been modified.
    fn package_for_save(&self) -> std::borrow::Cow<'_, Package> {
        if !self.modified {
            return std::borrow::Cow::Borrowed(&self.package);
        }
        let mut package = self.package.clone();
        if let Some(part) = package.part_mut(&self.doc_part_name) {
            part.data = self.tree.serialize();
        }
        std::borrow::Cow::Owned(package)
    }

    /// The underlying OPC package.
    pub fn package(&self) -> &Package {
        &self.package
    }

    /// Read access to the parsed main-document tree (used by handles).
    pub(crate) fn tree(&self) -> &XmlTree {
        &self.tree
    }

    /// Mutable access to the parsed main-document tree. Handing out this capability
    /// marks the document modified so that [`save`](Self::save) re-serializes it.
    pub(crate) fn tree_mut(&mut self) -> &mut XmlTree {
        self.modified = true;
        &mut self.tree
    }

    /// Build a qualified name in the document's WordprocessingML namespace, e.g.
    /// `qn("p")` → `"w:p"` (or just `"p"` when the main namespace is the default).
    pub(crate) fn qn(&self, local: &str) -> String {
        if self.wml_prefix.is_empty() {
            local.to_string()
        } else {
            format!("{}:{}", self.wml_prefix, local)
        }
    }

    /// The `w:body` element, if present.
    fn body(&self) -> Option<NodeId> {
        let root = self.tree.root();
        self.tree
            .children(root)
            .iter()
            .copied()
            .find(|&c| is_wml_element(&self.tree, c, "body"))
    }

    /// The document's body-level paragraphs, in order.
    ///
    /// These are the direct `w:p` children of `w:body` — matching python-docx's
    /// `Document.paragraphs`. Paragraphs nested inside tables are intentionally *not*
    /// included at this milestone.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// doc.add_paragraph("one");
    /// doc.add_paragraph("two");
    /// let texts: Vec<String> = doc.paragraphs().iter().map(|p| p.text(&doc)).collect();
    /// assert_eq!(texts, ["one", "two"]);
    /// ```
    pub fn paragraphs(&self) -> Vec<Paragraph> {
        let Some(body) = self.body() else {
            return Vec::new();
        };
        self.tree
            .children(body)
            .iter()
            .copied()
            .filter(|&c| is_wml_element(&self.tree, c, "p"))
            .map(Paragraph::from_node)
            .collect()
    }

    /// Append a new body paragraph, returning a handle to it.
    ///
    /// The paragraph is inserted before a trailing `w:sectPr` when one is a direct child
    /// of `w:body` (Word requires the body's section properties to come last). When
    /// `text` is non-empty a single run carrying it is added.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use docxml::Document;
    ///
    /// let mut doc = Document::new();
    /// let p = doc.add_paragraph("Signed and agreed:");
    /// assert_eq!(p.text(&doc), "Signed and agreed:");
    /// ```
    pub fn add_paragraph(&mut self, text: &str) -> Paragraph {
        let body = self.body().expect("document has a w:body");
        let name = self.qn("p");
        let p = self.tree_mut().create_element(name);

        // Keep a trailing w:sectPr last, per the WordprocessingML content model.
        let children = self.tree.children(body);
        let index = match children.last().copied() {
            Some(last) if is_wml_element(&self.tree, last, "sectPr") => children.len() - 1,
            _ => children.len(),
        };
        self.tree_mut().insert_child(body, index, p);

        let para = Paragraph::from_node(p);
        if !text.is_empty() {
            para.add_run(self, text);
        }
        para
    }
}

/// Determine the prefix the document root maps to a WordprocessingML main URI.
///
/// Scans the root element's namespace declarations for one bound to the transitional or
/// strict main URI, returning its prefix (empty string for the default namespace). Falls
/// back to `w` when the root declares none — the conventional prefix Word uses.
fn detect_wml_prefix(tree: &XmlTree) -> String {
    let root = tree.root();
    for (key, value) in tree.attrs(root) {
        if !WML_MAIN_URIS.contains(&value.as_str()) {
            continue;
        }
        if let Some(prefix) = key.strip_prefix("xmlns:") {
            return prefix.to_string();
        }
        if key == "xmlns" {
            return String::new();
        }
    }
    "w".to_string()
}
